app = 'trellix-clone'
primary_region = 'ord'

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
auto_rollback = true

[mounts]
destination = "/data"
source = "data"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = 10000
grace_period = "1s"
method = "get"
path = "/"
protocol = "http"
restart_limit = 0
timeout = 500
tls_skip_verify = false


[[services.ports]]
handlers = ["tls", "http"]
port = 443
